name: api-contract

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  api-contract:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm ci
      - run: npm run build
      - name: Start server
        run: npm run start & npx wait-on http://localhost:3000/api/health
      - name: Verify API health contract
        run: curl -sSf http://localhost:3000/api/health | grep 'ok'
