name: Python API CI

on:
  push:
    branches: [ main ]
    paths:
      - 'api/**'
  pull_request:
    paths:
      - 'api/**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./api

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m venv .venv
        source .venv/bin/activate
        pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install pytest # Install pytest for running tests

    - name: Test with pytest
      run: |
        source .venv/bin/activate
        pytest
