name: Vercel Deployment Integration

on:
  deployment_status:

jobs:
  update_project_board:
    runs-on: ubuntu-latest
    if: github.event.deployment_status.state == 'success' && github.event.deployment.environment == 'Production'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Find associated PR and Issue
        id: find_issue
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMIT_SHA: ${{ github.event.deployment.sha }}
        run: |
          echo "Finding PR for commit $COMMIT_SHA"
          PR_URL=$(gh pr list --search $COMMIT_SHA --state merged --json url -q '[0].url')
          if [ -z "$PR_URL" ]; then
            echo "No merged PR found for this commit."
            exit 0
          fi
          echo "Found PR: $PR_URL"

          echo "Finding linked issue..."
          ISSUE_URL=$(gh pr view $PR_URL --json closingIssuesReferences -q '.closingIssuesReferences.nodes[0].url')
          if [ -z "$ISSUE_URL" ]; then
            echo "No issue linked to this PR."
            exit 0
          fi
          echo "Found Issue: $ISSUE_URL"
          echo "ISSUE_URL=$ISSUE_URL" >> $GITHUB_OUTPUT

      - name: Label and Comment on Issue
        if: steps.find_issue.outputs.ISSUE_URL
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_URL: ${{ steps.find_issue.outputs.ISSUE_URL }}
          DEPLOYMENT_URL: ${{ github.event.deployment_status.target_url }}
        run: |
          echo "Applying 'Deployed' label to $ISSUE_URL"
          gh issue edit $ISSUE_URL --add-label "Deployed"

          echo "Commenting on $ISSUE_URL"
          gh issue comment $ISSUE_URL --body "🎉 Successfully deployed to production on Vercel: ${{ env.DEPLOYMENT_URL }}"
