name: Vercel Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      environment:
        description: "Target environment (preview|prod)"
        required: true
        default: preview

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Check required Vercel secrets
        run: |
          if [ -z "${{ secrets.VERCEL_TOKEN }}" ] || [ -z "${{ secrets.VERCEL_ORG_ID }}" ] || [ -z "${{ secrets.VERCEL_PROJECT_ID }}" ]; then
            echo "Missing one or more Vercel secrets (VERCEL_TOKEN, VERCEL_ORG_ID, VERCEL_PROJECT_ID)" >&2
            exit 1
          fi
      - run: npm ci
      - name: Pull Vercel Env
        run: |
          ENVIRONMENT=${{ github.event_name == 'workflow_dispatch' && (inputs.environment == 'prod' && 'production' || 'preview') || (github.event_name == 'push' && 'production' || 'preview') }}
          echo "Pulling env for: $ENVIRONMENT"
          npx vercel pull --yes --environment=$ENVIRONMENT --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build
        run: npx vercel build --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy
        run: |
          if [ "${{ github.event_name }}" = "push" ]; then
            npx vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
          elif [ "${{ github.event_name }}" = "workflow_dispatch" ] && [ "${{ inputs.environment }}" = "prod" ]; then
            npx vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
          else
            npx vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
          fi
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
      - name: Update Project Board - Deployed
        if: github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && inputs.environment == 'prod')
        env:
          GH_TOKEN: ${{ secrets.GH_PROJECT_TOKEN }}
          PROJECT_OWNER: Pinak-Setu
          PROJECT_NUMBER: "4"
          ISSUE_LABEL: Task
        run: |
          echo "Production deployment completed - updating project board"
          node scripts/move-to-deployed.js || echo "Project board update skipped (missing scopes or config)"
