name: Vercel Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      environment:
        description: "Target environment (preview|prod)"
        required: true
        default: preview

jobs:
  deploy:
    if: ${{ secrets.VERCEL_TOKEN && secrets.VERCEL_ORG_ID && secrets.VERCEL_PROJECT_ID }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm ci
      - name: Pull Vercel Env
        run: |
          ENVIRONMENT=${{ github.event_name == 'workflow_dispatch' && (inputs.environment == 'prod' && 'production' || 'preview') || (github.event_name == 'push' && 'production' || 'preview') }}
          echo "Pulling env for: $ENVIRONMENT"
          npx vercel pull --yes --environment=$ENVIRONMENT --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build
        run: npx vercel build --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy
        run: |
          if [ "${{ github.event_name }}" = "push" ]; then
            npx vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
          elif [ "${{ github.event_name }}" = "workflow_dispatch" ] && [ "${{ inputs.environment }}" = "prod" ]; then
            npx vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
          else
            npx vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
          fi
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
